name: Check for broken links
on:
  push:
  schedule:
    - cron: '0 5 * * SUN'

jobs:
  broken-link-check:
    runs-on: ubuntu-24.04
    name: Check for broken links in README.md
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Check for broken links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --exclude-loopback --root-dir ${{ github.workspace }} README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
